---
# init-kernel handlers

- name: Reload systemd
  ansible.builtin.command:
    cmd: systemctl daemon-reexec
  changed_when: true

- name: Restart sshd for limits
  ansible.builtin.systemd:
    name: "{{ 'ssh' if ansible_os_family == 'Debian' else 'sshd' }}"
    state: restarted
    daemon_reload: true
