---
# init-ssh handlers

- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: Restart sshd-emergency
  ansible.builtin.systemd:
    name: sshd-emergency
    state: restarted
    daemon_reload: true
