---
# init-ssh handlers

- name: Restart sshd
  ansible.builtin.systemd:
    name: "{{ 'ssh' if ansible_os_family == 'Debian' else 'sshd' }}"
    state: restarted

- name: Restart sshd-emergency
  ansible.builtin.systemd:
    name: sshd-emergency
    state: restarted
    daemon_reload: true
